export const BARRIOS_CALI = [
  'Terrón Colorado',
  'Vista Hermosa',
  'Aguacatal',
  'Santa Rita',
  'Santa Teresita',
  'Arboledas',
  'Normandía',
  'Juanambú',
  'Centenario',
  'Granada',
  'Versalles',
  'San Vicente',
  'Santa Mónica',
  'Prados del Norte',
  'La Flora',
  'La Campiña',
  'La Paz',
  'El Bosque',
  'Menga',
  'Ciudad Los Alamos',
  'Chipichape',
  'Brisas de los Alamos',
  'Urbanización La Merced',
  'Vipasa',
  'Urbanización La Flora',
  'Altos de Menga',
  'Senderos de la Flora',
  'El Nacional',
  'El Peñón',
  'San Antonio',
  'San Cayetano',
  'Los Libertadores',
  'San Juan Bosco',
  'Santa Rosa',
  'La Merced',
  'San Pascual',
  'El Calvario',
  'San Pedro',
  'San Nicolas',
  'El Hoyo',
  'El Piloto',
  'Navarro - La Chanca',
  'Jorge Isaacs',
  'Santander',
  'Porvenir',
  'Las Delicias',
  'Manzanares',
  'Salomia',
  'Fátima',
  'Sultana - Berlín - San Francisco',
  'Popular',
  'Ignacio Rengifo',
  'Guillermo Valencia',
  'La Isla',
  'Marco Fidel Suárez',
  'Evaristo García',
  'La Esmeralda',
  'Bolivariano',
  'Olaya Herrera',
  // ... puedes agregar todos los demás del backend
  // Por ahora usamos estos como ejemplo
].sort(); // Ordenar alfabéticamente
